### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by otreblan** [L603/SpaceClones#3]
Hay que encontrar una manera de cargar assets(Imágenes, sonidos, fuentes, .....) sin importar desde donde se ejecute el programa.
Debe funcionar cuando el ejecutable está en la carpeta en la que se compiló y también después de ser instalado en `/usr/bin`.
Estaba pensando en añadir [physfs](https://repology.org/project/physfs/versions) como una nueva dependencia.
Al parecer [supertux](https://github.com/supertux/supertux) lo usa para cargar sus assets.

**Comment by otreblan** [comment]
http://icculus.org/physfs/physfstut.txt

**Comment by Maniac95867** [comment]
a q te refieres con nueva dependencia?
Por q quieres poner imagenes o sonidos?

**Comment by otreblan** [comment]
> a q te refieres con nueva dependencia?
> Por q quieres poner imagenes o sonidos?

Un programa necesario para que esto funcione.
Pensaba usar imágenes para los sprites.

Al final no agregué physfs y en lugar puse unos macros para resolver el PATH de los assets.
